name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.x, 2.2.x, devel]
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      run: |
        sudo apt update
        sudo apt install -y make 
        sudo make install_mkcert
        mkcert -install
        mkcert example.com "*.example.com" example.test localhost 127.0.0.1 ::1
        nimble install -y --depsOnly
        cat .env >> $GITHUB_ENV
      #  cat ./example.com+5.pem
      #  cat ./example.com+5-key.pem
      #  echo $HYPERX_TEST_CERTFILE
      #  echo $HYPERX_TEST_KEYFILE
    - name: Run Interop Tests
      run: |
        (nimble interopserve &)
        sleep 10s
        nimble interoptest
    - name: Run tls examples
      run: |
        (nimble exampleserve &)
        sleep 10s
        nimble exampleclient
    - name: Run insecure examples
      run: |
        (nimble exampleserveinsecure &)
        sleep 10s
        nimble exampleclientinsecure
    - name: Run multi-thread examples
      run: |
        (nimble exampleservemultithread &)
        sleep 10s
        nimble exampleclientinsecure
    - name: Run Tests
      run: |
        (nimble testserve &)
        sleep 10s
        nimble testclient
    - name: Run Go server interop tests
      run: |
        curl -JLO "https://github.com/nitely/nim-grpc/releases/download/v0.1.0/go_server"
        chmod +x ./go_server
        (nimble gointeropserve &)
        sleep 10s
        nimble interoptest2
    - name: Run Go client interop tests
      run: |
        curl -JLO "https://github.com/nitely/nim-grpc/releases/download/v0.1.0/go_client"
        chmod +x ./go_client
        (nim c -r tests/interop/testserver.nim &)
        sleep 10s
        nimble gointeroptest
    - name: Run Functional Tests
      run: |
        (nimble testfuncserve &)
        sleep 10s
        nimble testfuncclient
